id: AB0843C4C
base_file: fFA54.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:39:27.224055
  last_modified_at: 2022-05-31 06:39:27.224060
