id: AB0843C4C
base_file: f5649.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:39:27.220236
  last_modified_at: 2022-05-31 06:39:27.220244
